# -*- coding: utf-8 -*-
"""ikv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10TEIz4FD-sBVrTcb2c_EzhvsIO3W0K3k

## New Matrix after Eliminating 2rd and 7th joint
"""

A13=dh(0.045,0,0.55,theta3)
A13

A68=dh(0,0,0.18,theta8)
A68

T08n = A01*A13*A34*A45*A56*A68
T08n

# now adding transformation matrices from the base to the ith frame
T01n=A01
T03n=A01*A13
T04n=A01*A13*A34
T05n=A01*A13*A34*A45
T06n=A01*A13*A34*A45*A56
T04n

z0n= sym.Matrix([0,0,1])
z1n= sym.Matrix(T01n[0:3,2])
z3n= sym.Matrix(T03n[0:3,2])
z4n= sym.Matrix(T04n[0:3,2])
z5n= sym.Matrix(T05n[0:3,2])
z6n= sym.Matrix(T06n[0:3,2])
z8n= sym.Matrix(T08n[0:3,2])
z8n

p0n= sym.Matrix([0,0,0])
p1n= sym.Matrix(T01n[0:3,3])
p3n= sym.Matrix(T03n[0:3,3])
p4n= sym.Matrix(T04n[0:3,3])
p5n= sym.Matrix(T05n[0:3,3])
p6n= sym.Matrix(T06n[0:3,3])
pn= sym.Matrix(T08n[0:3,3])
pn

pj1n = diff(p,theta1)
pj1n = pj1n.col_insert(1,sym.diff(pn,theta3))
pj1n = pj1n.col_insert(2,sym.diff(pn,theta4))
pj1n = pj1n.col_insert(3,sym.diff(pn,theta5))
pj1n = pj1n.col_insert(4,sym.diff(pn,theta6))
pj1n = pj1n.col_insert(5,sym.diff(pn,theta8))
pj1n

pj2n = z1n
pj2n = pj2n.col_insert(1,z3n)
pj2n = pj2n.col_insert(2,z4n)
pj2n = pj2n.col_insert(3,z5n)
pj2n = pj2n.col_insert(4,z6n)
pj2n = pj2n.col_insert(5,z8n)
pj2n

Jn = pj1n.row_insert(3,pj2n)
Jn

import matplotlib.pyplot as plt
ts = sym.Matrix([0,30,-45,0,75,90])*(pi/180)
n = 50
qv = np.linspace(float(pi/2), float((5*pi)/2),num=n)

JI = Jn.evalf(3, subs={theta1:ts[0],theta3:ts[1],theta4:ts[2],theta5:ts[3],theta6:ts[4],theta8:ts[5]})
JI

for i in range(0,n):
  dx = -10.0 * qv[i]  
  dz = 10.0 * qv[i]

  cinput = Matrix([dx,0.0, dz, 0.0, 0.0, 0.0])
  JI = Jn.evalf(3, subs={theta1:ts[0],theta3:ts[1],theta4:ts[2],theta5:ts[3],theta6:ts[4],theta8:ts[5]}).inv()
  
  dq = JI*cinput
  ts = ts + (dq*(5/n))
  tval = T08n.evalf(3, subs={theta1:ts[0],theta3:ts[1],theta4:ts[2],theta5:ts[3],theta6:ts[4],theta8:ts[5]})

  plt.scatter(tval[0,3],tval[2,3])

plt.show()